accounts/urls.py
# accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

myproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from myapp.views import index
from sign.views import signup
from test12.views import *
from table_test.views import *
from django.views.generic.base import TemplateView
from users import views as users_views
from core.views import *
from django.contrib.auth import views as auth_views

from django.views.generic.base import TemplateView



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^myview/$', index),
    url(r'^signup/$', signup),
    url(r'^sign_up/$', sign_up),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^sample/$',TemplateView.as_view(template_name='sample.html')),
    #url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^search/', search),
    url(r'^index/$', index1),
    url(r'^table/$', send),
    url(r'^order/$', submitOrder),
    url(r'^measure/$', setMeasurements),
    url(r'^printOrder/$', printOrder),
    url(r'^table_test/',include('table_test.urls')),
    url(r'^register/$', users_views.register, name = 'register')

    


]

table_test/urls.py
from django.conf.urls import url
from table_test import views
# SET THE NAMESPACE!
app_name = 'table_test'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

table_test/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
# Create your models here.

from django.db import models

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    city = models.CharField(max_length=60)

class Order(models.Model):
	orderID = models.CharField(max_length=30)
	userID = models.CharField(max_length=30)
	address1 = models.CharField(max_length=60)
	address2 = models.CharField(max_length=60)
	payment = models.CharField(max_length=30)
	status = models.CharField(max_length=30)

class Measurements(models.Model):
	orderID = models.CharField(max_length=30)
	jeans1 = models.CharField(max_length=30)
	thread1 = models.CharField(max_length=30)
	jeans2 = models.CharField(max_length=30)
	thread2 = models.CharField(max_length=30)
	tailor1 = models.CharField(max_length=30)
	tailor2 = models.CharField(max_length=30)
	tailor3 = models.CharField(max_length=30)

class User(models.Model):
	userID = models.CharField(max_length=30) 
	gmail = models.EmailField()
	firstname = models.CharField(max_length=30)
	lastname = models.CharField(max_length=30)
	zipcode = models.CharField(max_length=30)
	address1 = models.CharField(max_length=60)
	address2 = models.CharField(max_length=60)
	city = models.CharField(max_length=30)

class UserProfileInfo(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	portfolio_site = models.URLField(blank=True)
	#profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
 	
 	def __str__(self):
         return self.user.username

table_test/forms.py
from __future__ import unicode_literals

from django import forms
from table_test.models import UserProfileInfo
from django.contrib.auth.models import User
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
         model = User
         fields = ('username','password','email')
class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('portfolio_site',)

table_test/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from table_test.models import * 
from table_test.forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required



# Create your views here.



def send(request):
    p = Publisher(name='who am I', city='Berkeley')
    p.save()
    return HttpResponse((p.city,p.name))


def submitOrder(request):
    order = Order()
    order.orderID = 'ord4'
    order.userID = 'user123'
    order.address1 = 'amaraddress11'
    order.address2 = 'amaraddress12'
    order.save()
    return HttpResponse('mone hoy save hoise')

def setMeasurements(request):
    mes = Measurements()
    mes.orderID = 'ord456'
    mes.jeans1 = 'myjeans1'
    mes.thread1 = 'mythread1'
    mes.save()
    return HttpResponse(mes)


def printOrder(request):
    order_list = Order.objects.exclude(orderID='ord2')

    #return HttpResponse(order_list[1].orderID)
    return render(request, 'tablePrint.html',{'messages': order_list})



def index(request):
    return render(request,'table_test/index.html')
@login_required

def special(request):
    return HttpResponse("You are logged in !")
@login_required

def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'table_test/login.html', {})

table_test/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'table_test:index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'table_test:register' %}">Register</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'dappx:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

table_test/templates/index.html
{% extends "table_test/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Djungle !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

table_test/templates/login.html
{% extends 'table_test/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'dappx:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

table_test/templates/registration.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

table_test/templates/tablePrint.html
<!DOCTYPE html>
<html>
    <head>
        <title>My view123</title>
    <head>
    <body>
        <h1>Hello World123!</h1>

        {% for message in messages %}
            <p> {{message.userID}} </p>
	    <p> {{message.orderID}} </p>
        {% endfor %}

    </body>
<html>